### PR TITLE
Make pages translatable

### PR DESCRIPTION
**Pull request by schneikai**
Hi! I added a feature that makes it possible to translate individual pages. I did this because I needed to have pages in different languages but wasn't completely happy with how Comfy is handling this via the mirroring feature right now.

Here are some screenshots
screenshot
screenshot
screenshot
screenshot

Hope you like it.

### CODE REVIEW

**Comment by arthurtalkgoal** [comment]
Can I ask if this pull request can be merged?

Mutli Language is a very important for our site. I am using the pull request commits now.

**Comment by arthurtalkgoal** [comment]
Hi Guys,

Do you think it's suitable to add translation into snippets and/or Layouts ? I am using  7bbf7a9 and I can only find the Translation button in Pages.

If you agreed, I can PR codes for the translation of snippets/layout

**Comment by schneikai** [comment]
Translated snippets make sense for me. Translated layouts sound strange :) If thers something to translate in the layout you could use I18n or maybe a snippet. Just my 2 cents of course :)

**Comment by arthurtalkgoal** [comment]
Hi @schneikai , 

I really need a way to translate my repeating footer/header contents, Snippets works very well. 

I will go ahead the translation codes soon after I deploy the current version. I think I need to switch to your repos instead of this comfy master; since i am not sure when they will merge the PR.

**Comment by arthurtalkgoal** [comment]
Hi @schneikai , I found that preload the blocks content in New Translation is useful. Do you think it is a good feature? I can PR.

**Comment by schneikai** [comment]
What do you mean exactly?

**Comment by arthurtalkgoal** [comment]
When we click "translate" button, the page blocks content are empty.  

I can default the translation contents with the page content.

**Comment by arthurtalkgoal** [comment]
Here is my translation controller decorator: 

```
  before_action :preload_page_values, :only =>[:new]
  
  protected 
  
  def preload_page_values
    return unless @translateable.present?
    blocks_attributes=[]
    @translateable.blocks.each do |b|
      blocks_attributes << {:identifier => b.identifier, :content => b.content}
    end
    @translation.blocks_attributes = blocks_attributes
  end
```

**Comment by schneikai** [comment]
Ah, cool! But does this work for page file fields too?

**Comment by schneikai** [comment]
@GBH I have a failing test because of the new i18n test and missing translations. I would like to add them of course but don't know how. My language skills are just english, german and some weird german dialect ;) It's this block here https://github.com/comfy/comfortable-mexican-sofa/pull/522/files#diff-37c9b835927e3c363588f172de9bb6faR167

**Comment by GBH** [comment]
@schneikai just populate everything with english version. That's what I do normally.

**Comment by arthurtalkgoal** [comment]
Hi @schneikai , it is for page content blocks translations only.

Let me know if that file field need the default value too.

**Comment by schneikai** [comment]
@arthurtalkgoal maybe you could just check what happens when there is a *cms:page_file* tag in the layout... not that something crashes...

**Comment by arthurtalkgoal** [comment]
Oh, Hi @schneikai , Ok. Let me fix them.

**Comment by sowasred2012** [comment]
Hi @schneikai - I love this idea and I'm trying to use it, but getting stuck at what the route for a translated page would be:

Given I've created a site at `/example-cms`, and a page with a locale of en whose content I can see by visiting mysite.com/example-cms, when I create a French translation for that page, what should the path be?

**Comment by schneikai** [comment]
Create a method ```cms_locale``` in your application controller and return the locale you want to use for the current request. For example on my website I return the locale base on the current requests top level domain.

https://github.com/comfy/comfortable-mexican-sofa/pull/522/files#diff-b791b6919252468c282750a0254f7704R7

**Comment by sowasred2012** [comment]
Awesome, that's done it - thanks very much!

**Comment by amuntasim** [comment]
@schneikai, How can I use this feature?

**Comment by schneikai** [comment]
schneikai/comfortable-mexican-sofa:add_translations

**Comment by amuntasim** [comment]
Is there any migration script to update the schema, or I have to reset the schema? @schneikai

**Comment by amuntasim** [comment]
btw, I've create one myself as I have existing data.

class AddCmsTranslations < ActiveRecord::Migration
  def change
    create_table :comfy_cms_translations do |t|
      t.references :translateable, :polymorphic => true
      t.string  :locale,           :null => false
      t.integer :target_page_id
      t.string  :label,            :null => false
      t.string  :slug
      t.string  :full_path,        :null => false
      t.text    :content_cache,    16777215
      t.boolean :is_published,     :null => false, :default => true
      t.timestamps
    end
    add_index :comfy_cms_translations, [:full_path]
    add_index :comfy_cms_translations, [:translateable_id, :translateable_type],
              :name => 'index_cms_translations_on_tid_and_ttype'
  end
end

**Comment by schneikai** [comment]
Cool. If you like you could add it to my branch.

**Comment by amuntasim** [comment]
Just create a PR, please review at your convenient time.

**Comment by fabn** [comment]
@GBH Any news on merging this?

**Comment by wintondeshong** [comment]
+1 on merge

**Comment by ethier** [comment]
:thumbsup:

**Comment by arsandov** [comment]
Merge? :+1:

**Comment by GBH** [comment]
Only 3 years later there's no more site mirroring and page translations are in. Used this PR as a reference a bit. So now:

* Page can have many Translations attached.
* Each translation is defined by locale (must be different than the Site locale)
* Translations have many Fragments (formerly known as Blocks)
* Translations do not have localised slugs as complexity shoots up to stratosphere with that (maybe in the future)
* When content is served, locale is checked. If it's different than the one defined on Site record, we will attempt to grab appropriate Translation record for the found Page. Translation fragments and Translation `content_cache` are assigned to `@cms_page` so we don't need to handle Translation any differently.
* There's a bit of DB churn for this. Maybe need to add frag cache...

**Pull request closed without merging**
