### PR TITLE
Duplicate #892 - Rails 6 save stack too deep on File upload

### PR DESCRIPTION
**Pull request by nitsujri**
### Summary

All credit goes to @Tongboy: https://github.com/comfy/comfortable-mexican-sofa/pull/892

PR is failing simple specs that just need to be rebase. No movement has been had for 2 weeks.

Feel free to close if primary PR regains activity.

PR Fixes this issue: https://github.com/comfy/comfortable-mexican-sofa/issues/898

### CODE REVIEW

**Comment by nitsujri** [comment]
Pinging @morgant for eyes

**Comment by unRARed** [comment]
Is something holding this up? We've moved to Rails 6 and can confirm this fix solves the recursive ActiveStorage file upload problem.

**Comment by nitsujri** [comment]
Pinging @GBH @morgant for review/merge. Thanks!

**Comment by GBH** [comment]
Thanks!

Sorry about my inactivity. I'll try to clean up stuff and do a gem release by the end of the month.

**Comment by morgant** [comment]
Thanks @GBH!

**Pull request merged**
