### PR TITLE
Improve README to help newcomers

### PR DESCRIPTION
**Pull request by Onumis**
### Summary

I was trying to make an app work with Rails 5.2, but it's not really coming along.
So I fell back to 5.1, and noticed it's (unnecessarily) a much harsh world.

This info should better help others like me.

### CODE REVIEW

**Comment by GBH** [comment]
I'm working right now on releasing 2.0.0.beta gem as Rails 5.2.beta got published. I don't think I can support 5.1 as it's a mess compared to 5.0 even.

What issues did you have with Rails 5.2?

**Comment by Onumis** [comment]
Not with CMS directly, but with a dependency of ActiveAdmin: `https://github.com/activerecord-hackery/polyamorous/issues/26`

**Comment by GBH** [comment]
Ah. That sucks. Maybe 5.2 going beta will expedite that bug fixing.

**Comment by GBH** [comment]
I adjusted readme and put not in the wiki.

**Pull request closed without merging**
