### PR TITLE
use the `host_with_port` to lookup the site

### PR DESCRIPTION
**Pull request by dougalcorn**
this matches what `Comfy::Cms::BaseController.load_cms_site`

### CODE REVIEW

**Comment by jume-dev** [comment]
would be good, if this was implemented

**Comment by GBH** [comment]
Can you guys explain what this is for? I vaguely remember that adding port in site.host was messing up lookups.

**Comment by jume-dev** [comment]
For me it's mainly for my development system, where my server is on localhost:8081

**Comment by andywenk** [comment]
I would love to see this PR merged

**Comment by devshane** [comment]
:+1: 

I think I remember it being particularly problematic with custom code/controllers.

**Comment by andywenk** [comment]
thanks @GBH ;-)

**Pull request merged**
