### PR TITLE
Converts CoffeeScript to JavaScript + cleanup

### PR DESCRIPTION
**Pull request by glebm**
Also adds `dispose` to all widgets that need it, fixing memory leaks on "fragment" switching and paving the road for Turbolinks support.
Fixes category creation.

CoffeeScript dependency is now gone! :tada:

### CODE REVIEW

**Comment by GBH** [comment]
Awesome work. Can you please check system tests? Something's is blowing up.

**Comment by glebm** [comment]
I can't reproduce the error by repeating the CI steps manually, and I'm having issues with running system tests locally at the moment (`Selenium::WebDriver::Error::WebDriverError: disconnected: unable to connect to rendere`)

**Comment by glebm** [comment]
Looks like the issue may be that the version of chromedriver on CI is < 2.35

**Comment by glebm** [comment]
Yep, that was it.

**Comment by GBH** [comment]
Seems like it was it

**Pull request merged**
