### PR TITLE
Integrate files library better with PageFiles and Redactor

### PR DESCRIPTION
**Pull request by schneikai**
Thanks for the Redactor integrations. It's very cool!
This pull request makes changes to Redactor so that if you insert images or files via Redactor it shows the Comfy files library instead of the default Redactor files- and image manager. 

The pull request also introduces a new tag "cms:page_file_library". This tag basically works like "cms:page_file" but allows to select a file from the Comfy files library.

I think it would have been nice if I would've just changed the "cms:page_file" tag to use the library. You could remove a lot of code for the upload and the files association on blocks. But the crop/dimension feature on the current "cms:page_file" can't be reproduced because it would need to happen in the library. Also selecting multiple files does not yet work for the new "cms:page_file_library" tag.

You have this other task on updating the tag system. Maybe that's a good time to clean up a little bit especially the cms:file, cms:page_file, cms:page_files and cms:page_file_library tags :)

I made a little Screencast to showcase the changes
https://docs.google.com/file/d/0Byd7rfwOIEzYaElIQTV6YWd5VEE/edit?pli=1

Hope you like it!

### CODE REVIEW

**Comment by GBH** [comment]
This is awesome. I'll try to review and merge it this weekend. :+1:

**Comment by GBH** [comment]
Hi @schneikai Do you mind isolating file/image manager replacement for wysiwyg and making pull request just for that? Let's hold off with the new tag as I think we can reuse existing.

**Comment by schneikai** [comment]
Will try that tomorrow.

**Comment by andywenk** [comment]
@schneikai woot - this is cool! I thought it would be nice to change the Redactor Image and FileUpload popups instead of showing the original Comfy files library because I really like the way Redactor shows the images. Would that be a lot of effort. I assume it could be placed in a Redactor Comfy Plugin which extends the existing behaviour with Comfy behaviour. What are your thoughts here?

**Comment by moeffju** [comment]
@schneikai Any updates on this pull request? It looks like a good solution for generic file selection within comfy without requiring deeper changes in redactor itself, but I’d prefer to use it if it was merged into comfy… do you plan on updating this PR soon, or would you be okay with me creating a new derivative PR?

**Comment by schneikai** [comment]
@andywenk I think having just one way of selecting files would be less code and more easy to maintain.

@moeffju I couldn't find time to isolate Redactor changes into a new PR as @GBH requested. If you have time, do it :)

**Comment by andywenk** [comment]
@schneikai ack! Let's go with the approach @moeffju is following now ;-)

**Comment by moeffju** [comment]
I’ll whittle this PR down and turn it into a new one then.

**Comment by moeffju** [comment]
@schneikai Sorry, I must have misunderstood you or @GBH. I was suggesting to reduce this pull request by basically only removing `lib/comfortable_mexican_sofa/tags/page_file_library.rb` so that there will not be a new tag. The previously existing `{cms:page_file:identifier}` still works just as before. (Although tbh I think the new tag would be super useful; as `page_file` only allows you to upload new files and not pick from the library.)

**Comment by schneikai** [comment]
No, you understand it right I think. GBH only wanted to have the new tag removed from the PR.

**Comment by moeffju** [comment]
@schneikai Ok, right. Since I have a deadline to keep, I have merged your PR wholesale into our fork. If I find the time, I might still update this, but it could be a while.

@GBH I agree with @schneikai that it makes sense to consolidate all the file handling into the file library, thus also consolidating all the tags. Whether you do that by extending cms:page_file or by merging cms:page_file_library does not make much of a difference, does it?

@schneikai Are there any precautions against files that are in use on a page being deleted from the library?

**Comment by schneikai** [comment]
No, there are no checks if files are in use yet.

**Comment by GBH** [comment]
While I still like the idea of changing default redactor file picker, this PR is way too old and in 2.0 here are too many changes. Closing this.

**Pull request closed without merging**
