### PR TITLE
Making Redactor’s field be resizable

### LINKED ISSUE #729: Redactor's textarea could be resizable
Surprised nobody seems to have requested this feature before, or rather that I am the only one who cares about perhaps trivial a thing haha. 😊 
Will come up with a quick patch for this and PR it, if you all think it's worth it.

### PR DESCRIPTION
**Pull request by hallaathrad**
Added the behaviour both to the regular and the code view.
Closes #729.

### CODE REVIEW

**Comment by hallaathrad** [comment]
Weird CI error from paperclip... not related to this submission. @GBH Wanna give it a look? I think this feature is worth it for UX.

**Comment by elyalvarado** [comment]
@hallaathrad In travis Rails version 4.2 is failing in ruby 2.0.0 because paperclip 5.1 requires in unsupported in ruby 2.0. That is what's causing the CI error

**Comment by hallaathrad** [comment]
@elyalvarado but it not something related to my submission, right?

**Comment by elyalvarado** [comment]
No, it's not. It will even fail on the master branch without any changes

**Comment by GBH** [comment]
👍

**Pull request merged**
