### PR TITLE
Greek Translation

### PR DESCRIPTION
**Pull request by man0s**
- Added Greek Translation Version 1.0

### CODE REVIEW

**Comment by GBH** [comment]
Thanks! 

For completeness sake, do you mind adding it to the blog too? It has a tiny locale file: https://github.com/comfy/comfy-blog/issues/48

**Comment by man0s** [comment]
@GBH Absolutely! No problem.

**Comment by GBH** [comment]
@man0s Also it seems that Redactor does't have GR locale by default. I moved in EN as a placeholder so editor doesn't crash. If you have time: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/lib/redactor/i18n/gr.js

**Comment by man0s** [comment]
@GBH Ok give me some minutes 😄

**Pull request merged**
