### PR TITLE
Updates version 1 to work with Rails 5.2

### PR DESCRIPTION
**Pull request by kirichkov**
### Summary

I've made some progress in getting version 1.12 to be compatible with Rails 5.2. This PR is to ask whether such submissions will be accepted at all, given that now there is version 2 out.

My main drive for working on this is the non-backwards-compatible nature of version 2. I'd much rather stay on version 1 and not dive in messy data migrations (I did try, it's a huge mess moving my data).

Some notes:

1.  I still have 2 tests which are failing, although the database content suggests they shouldn't be. I'll figure it out and push.
2. Because of braking changes in rails 5.2 this release **IS NOT** backwards compatible with rails versions below 5.1. Looking at the changes It will probably work, with mirrored sites not being properly updated.
3. I'll be looking into bringing the blog module in line too.
4. The main idea is to keep version 1 working with newer versions of rails without introducing any new features. Those should go towards version 2.

### CODE REVIEW

**Comment by GBH** [comment]
That's really the reason why I did a major release that's not compatible with anything lower than 5.2. I can't really merge this into 1.12 as it breaks everything.

If you want to maintain fork for 1.12 that works with Rails 5.2 that would be great. Can link to it from the Readme.

**Comment by GBH** [comment]
I think bumping to 1.13.0 might work. 1.12 stays in Rails 4 and this one is for 5.2. Obviously there will no new features going into this branch.

**Comment by kirichkov** [comment]
That works for me and I think everyone else. After all if someone needs a feature there’s numerous ways for them to add it without directly modifying the core code.

I’ll try to resolve the 2 failing tests by the end of the weekend.

**Comment by kirichkov** [comment]
All tests are passing.

**Comment by robmathews** [comment]
@kirichkov I managed to do the upgrade, but it was hellish and I never was able to migrate the files across. I completely agree with your idea +1
@GBH you planning on giving the PRs any love anytime soon? thanks!

**Comment by kirichkov** [comment]
Yeah, I also managed to migrate everything but the files, which was the real incentive to keep version 1 working. As a matter of fact I spent more time migrating data to v2, then updating v1, a lot more.

**Comment by GBH** [comment]
Merged into https://github.com/comfy/comfortable-mexican-sofa/tree/1.13

**Comment by kirichkov** [comment]
Any plans to push a 1.13 gem to rubygems?

**Pull request closed without merging**
