### PR TITLE
Allow Site model to handle multiple sites on a basepath

### PR DESCRIPTION
**Pull request by nisevi**
Fixes issue https://github.com/comfy/comfortable-mexican-sofa/issues/830

Changes were made to use what the latest version of this CMS is using in the `Site` [model](https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/models/comfy/cms/site.rb#L36)

### CODE REVIEW

**Comment by nisevi** [comment]
Hi there @GBH I have tested this changes against the APP that I shared earlier and now `Site` model is able to handle multiple sites.

Sorry if this PR doesn't go against version that you were expecting for. First time that I created a branch from a tag (1.12.10) and pushed as a PR against it. So feel free to close it and open a new one with this fixes if you want :+1: 

I will really appreciate if you release a 1.12.11 version that we could use with rails 5.0 :rocket:

**Comment by GBH** [comment]
Looks good, but can you please add a supporting test for it as well? Thanks 👍

**Comment by nisevi** [comment]
Sure thing I will add the related tests :+1:

**Comment by nisevi** [comment]
@GBH I have added the related tests :+1: 

I also created a rake task for running model tests, in this way it was easy for me to only run the tests I wanted and I cleaned some white spaces. But I totally understand if you don't want to include those changes since they are not related to this fix, so let me know and I can revert them :robot:

**Comment by nisevi** [comment]
@GBH sorry to bother you on this matter but, is it possible to have a new release with this fix today?

**Comment by GBH** [comment]
I'll review and will release later tonight, hopefully 👍

**Comment by nisevi** [comment]
Sorry to bother you @GBH but have you had the opportunity to look at this?

**Comment by GBH** [comment]
Sorry, I've been very busy lately. This PR will be the first one to merge!

**Comment by GBH** [comment]
Merged and 1.12.11 is out.

**Comment by nisevi** [comment]
Yay!!! You don't have idea how much I appreciate your efforts!!! Thank you man!!! :rocket:

**Pull request merged**
